# Exposer browsersync port 3000
version: '3.6'
services:
  web:
    ports:
      - "127.0.0.1:$DDEV_HOST_HTTPS_PORT:8080"
    environment:
      -  HTTP_EXPOSE=${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}:8025,8081:8080
      -  HTTPS_EXPOSE=${DDEV_ROUTER_HTTPS_PORT}:80,${DDEV_MAILHOG_HTTPS_PORT}:8025,8080:8080
